dist: bionic
language: bash
cache:
- "$HOME/.ccache"
addons:
  apt:
    packages:
    - ccache
services:
- docker
before_install:
- docker pull m0rf30/arch-arm-crosscompile
script:
- docker run -u root -v $HOME/.ccache:/ccache -v $(pwd):/workspace m0rf30/arch-arm-crosscompile:latest
  bash -c "cd /workspace/; CCACHE_DIR=/ccache ./build.sh"
deploy:
  provider: releases
  api_key:
    secure: Gje1Adlo8jh3B9GvyGCC8PumiXFqziQA2h4wIdyAZ/E53XzvwNWJ+UxDbRnkcoGE2lY+q3LfsuqxZS/Z7qMuYt1YQtW2p2/1CYjXbBq4jmMMrDP+fkQ6hdfN8MNGawx64rPv5GohhlZJ+mHdctu9qvMIg22VqrRv8Baw6p9OLpE5SVaLLxFFYv0ryqCZyUM6eZntuLoMxmLveBtd47f0s9bly73C3bbhhzR9HNHY49krUfmhCWTshIwBzxkqQcKVOggRDxOnoaUbXLdB/cPKXB/L289ePbAFjX6zvqhPmgi3eMz65Dv6U7zNknZNTWF99V9wZYVpM7wEpssT4nIl+FnxtbBdcLAg4EX1tOL5FfI0yJBf/luK3OvjZm0KJuKdLjRt/ONq98PP7orV2yAi/lHa2OfCE8jFk4Yv/MTrA31+O2sYDvogDTO0zL+4fThVIEKRp4PO3+szKq29QWASNiJFLthgVJSf600WFDi61ZD6dhYmhNbUYQKIzV0gZJU26rmX1nvjPMySz3ZGI4nZXOGf6LKlvN/n19ih8N4F8eyfPrulc+YPynuaHymwmOKBd/zEd0UX7jYiB+DXhQ0YkAsjr/Zty0/8PkcXz/8K+Htb4o4l2i20zo9lCeffgbrHEaADObapa/ysAxMTTgUOo/7uaDJGUgES9lThmQP0xpQ=
  file_glob: true
  skip_cleanup: true
  file: build/*
  on:
    repo: M0Rf30/qemu-kernel-rpi1
    branch: master
    tags: false
